#ifndef HUAWEICLOUD_SDK_CODEHUB_V4_CodeHubExport_H_
#define HUAWEICLOUD_SDK_CODEHUB_V4_CodeHubExport_H_

#include <huaweicloud/core/EXPORT.h>

#if defined(HUAWEICLOUD_SHARED)
#	if defined(HUAWEICLOUD_CODEHUB_V4_SHARED)
#		define HUAWEICLOUD_CODEHUB_V4_EXPORT HUAWEICLOUD_EXPORT
#	else
#		define HUAWEICLOUD_CODEHUB_V4_EXPORT HUAWEICLOUD_IMPORT
#	endif
#else
#	define HUAWEICLOUD_CODEHUB_V4_EXPORT
#endif

#endif // !HUAWEICLOUD_SDK_CODEHUB_V4_CodeHubExport_H_