#ifndef HUAWEICLOUD_SDK_DBSS_V1_DbssMeta_H_
#define HUAWEICLOUD_SDK_DBSS_V1_DbssMeta_H_

#include <huaweicloud/core/http/HttpRequestDef.h>
#include <huaweicloud/dbss/v1/DbssExport.h>

namespace HuaweiCloud {
namespace Sdk {
namespace Dbss {
namespace V1 {

using namespace HuaweiCloud::Sdk::Core::Http;

class HUAWEICLOUD_DBSS_V1_EXPORT  DbssMeta {
public:
    static HttpRequestDef genRequestDefForAddAuditAgent();
    static HttpRequestDef genRequestDefForAddAuditDatabase();
    static HttpRequestDef genRequestDefForAddAuditDatabaseNew();
    static HttpRequestDef genRequestDefForAddRdsDatabase();
    static HttpRequestDef genRequestDefForAddRdsDatabaseNew();
    static HttpRequestDef genRequestDefForAddRdsNoAgentDatabase();
    static HttpRequestDef genRequestDefForBatchDeleteAuditScope();
    static HttpRequestDef genRequestDefForBatchSetAuditAlarmLogStatus();
    static HttpRequestDef genRequestDefForBindDbEncryptEip();
    static HttpRequestDef genRequestDefForBindDbOmEip();
    static HttpRequestDef genRequestDefForChangeDbEncryptSecurityGroup();
    static HttpRequestDef genRequestDefForChangeDbOmSecurityGroup();
    static HttpRequestDef genRequestDefForConfirmUpgradeAudit();
    static HttpRequestDef genRequestDefForCountDbAccountSession();
    static HttpRequestDef genRequestDefForCountDbClientSession();
    static HttpRequestDef genRequestDefForCountInjectionStatistics();
    static HttpRequestDef genRequestDefForCountOperationStatistics();
    static HttpRequestDef genRequestDefForCountRiskTrendStatistics();
    static HttpRequestDef genRequestDefForCountSessionStatistics();
    static HttpRequestDef genRequestDefForCountSqlStatistics();
    static HttpRequestDef genRequestDefForCountSqlTrendStatistics();
    static HttpRequestDef genRequestDefForCreateAuditRiskRule();
    static HttpRequestDef genRequestDefForCreateAuditScopeRule();
    static HttpRequestDef genRequestDefForCreateDbEncryptInstancePeriod();
    static HttpRequestDef genRequestDefForCreateDbOmInstancePeriod();
    static HttpRequestDef genRequestDefForCreateInstancesPeriodOrder();
    static HttpRequestDef genRequestDefForCreateInstancesPeriodOrderNew();
    static HttpRequestDef genRequestDefForCreateReport();
    static HttpRequestDef genRequestDefForCreateSensitiveMaskRule();
    static HttpRequestDef genRequestDefForDeleteAuditAgent();
    static HttpRequestDef genRequestDefForDeleteAuditAlarmLog();
    static HttpRequestDef genRequestDefForDeleteAuditBackupTask();
    static HttpRequestDef genRequestDefForDeleteAuditDatabase();
    static HttpRequestDef genRequestDefForDeleteAuditDatabaseNew();
    static HttpRequestDef genRequestDefForDeleteAuditReport();
    static HttpRequestDef genRequestDefForDeleteAuditRuleRisk();
    static HttpRequestDef genRequestDefForDeleteAuditScope();
    static HttpRequestDef genRequestDefForDeleteDbEncryptInstance();
    static HttpRequestDef genRequestDefForDeleteDbOmInstance();
    static HttpRequestDef genRequestDefForDeleteInstances();
    static HttpRequestDef genRequestDefForDeleteInstancesNew();
    static HttpRequestDef genRequestDefForDeleteSensitiveRules();
    static HttpRequestDef genRequestDefForDownloadAuditAgent();
    static HttpRequestDef genRequestDefForDownloadAuditReport();
    static HttpRequestDef genRequestDefForListAlarmTopicConfigInfo();
    static HttpRequestDef genRequestDefForListAlarmTopicConfigInfoNew();
    static HttpRequestDef genRequestDefForListAuditAgent();
    static HttpRequestDef genRequestDefForListAuditAlarmLog();
    static HttpRequestDef genRequestDefForListAuditAlarmLogNew();
    static HttpRequestDef genRequestDefForListAuditBackupInfo();
    static HttpRequestDef genRequestDefForListAuditBackupRiskTemplates();
    static HttpRequestDef genRequestDefForListAuditDatabases();
    static HttpRequestDef genRequestDefForListAuditDatabasesNew();
    static HttpRequestDef genRequestDefForListAuditInstanceJobs();
    static HttpRequestDef genRequestDefForListAuditInstanceJobsNew();
    static HttpRequestDef genRequestDefForListAuditInstances();
    static HttpRequestDef genRequestDefForListAuditInstancesNew();
    static HttpRequestDef genRequestDefForListAuditObsBuckets();
    static HttpRequestDef genRequestDefForListAuditOperateLogs();
    static HttpRequestDef genRequestDefForListAuditOperateLogsNew();
    static HttpRequestDef genRequestDefForListAuditReportTemplates();
    static HttpRequestDef genRequestDefForListAuditReports();
    static HttpRequestDef genRequestDefForListAuditRuleRisks();
    static HttpRequestDef genRequestDefForListAuditRuleRisksNew();
    static HttpRequestDef genRequestDefForListAuditRuleScopes();
    static HttpRequestDef genRequestDefForListAuditRuleScopesNew();
    static HttpRequestDef genRequestDefForListAuditSensitiveMasks();
    static HttpRequestDef genRequestDefForListAuditSensitiveMasksNew();
    static HttpRequestDef genRequestDefForListAuditSqls();
    static HttpRequestDef genRequestDefForListAuditSqlsNew();
    static HttpRequestDef genRequestDefForListAuditSummaryInfos();
    static HttpRequestDef genRequestDefForListAuditTrendHistory();
    static HttpRequestDef genRequestDefForListAvailabilityZoneInfos();
    static HttpRequestDef genRequestDefForListAvailabilityZoneInfosNew();
    static HttpRequestDef genRequestDefForListDbEncryptInstances();
    static HttpRequestDef genRequestDefForListEcsSpecification();
    static HttpRequestDef genRequestDefForListEcsSpecificationNew();
    static HttpRequestDef genRequestDefForListInstances();
    static HttpRequestDef genRequestDefForListRdsDatabases();
    static HttpRequestDef genRequestDefForListSqlInjectionRules();
    static HttpRequestDef genRequestDefForRebootAuditInstance();
    static HttpRequestDef genRequestDefForRebootAuditInstanceNew();
    static HttpRequestDef genRequestDefForRebootDbEncryptInstance();
    static HttpRequestDef genRequestDefForRebootDbOmInstance();
    static HttpRequestDef genRequestDefForResetDbEncryptPassword();
    static HttpRequestDef genRequestDefForResetDbOmPassword();
    static HttpRequestDef genRequestDefForRestoreAuditBackup();
    static HttpRequestDef genRequestDefForRetryAuditBackupTask();
    static HttpRequestDef genRequestDefForSetAlarmTopicConfigInfo();
    static HttpRequestDef genRequestDefForSetAlarmTopicConfigInfoNew();
    static HttpRequestDef genRequestDefForSetAuditAlarmLogStatus();
    static HttpRequestDef genRequestDefForSetAuditAutoBackupTemplate();
    static HttpRequestDef genRequestDefForSetAuditBackupRiskSwitch();
    static HttpRequestDef genRequestDefForSetAuditBackupSwitch();
    static HttpRequestDef genRequestDefForSetAuditInstanceTimeZone();
    static HttpRequestDef genRequestDefForSetAuditScopeRuleSwitch();
    static HttpRequestDef genRequestDefForSetRiskOperationPolicy();
    static HttpRequestDef genRequestDefForSetRiskRuleRank();
    static HttpRequestDef genRequestDefForSetSensitiveMaskRuleSwitch();
    static HttpRequestDef genRequestDefForSetSensitiveResultSwitch();
    static HttpRequestDef genRequestDefForSetSensitiveSwitch();
    static HttpRequestDef genRequestDefForShowAuditBackRiskTemplate();
    static HttpRequestDef genRequestDefForShowAuditBackupStatus();
    static HttpRequestDef genRequestDefForShowAuditQuota();
    static HttpRequestDef genRequestDefForShowAuditQuotaNew();
    static HttpRequestDef genRequestDefForShowAuditRuleRisk();
    static HttpRequestDef genRequestDefForShowAuditRuleRiskNew();
    static HttpRequestDef genRequestDefForShowAuditStatistics();
    static HttpRequestDef genRequestDefForShowAuditTaskStatus();
    static HttpRequestDef genRequestDefForShowAuditTopicReportSchedulerConfig();
    static HttpRequestDef genRequestDefForShowAuditUpgradeStatus();
    static HttpRequestDef genRequestDefForShowBackupRiskBucketPath();
    static HttpRequestDef genRequestDefForShowInstanceMonitorInfo();
    static HttpRequestDef genRequestDefForShowInstanceQuota();
    static HttpRequestDef genRequestDefForShowSensitiveMaskSwitch();
    static HttpRequestDef genRequestDefForShowSensitiveResultSwitch();
    static HttpRequestDef genRequestDefForShowServerVersion();
    static HttpRequestDef genRequestDefForShowSqlDetail();
    static HttpRequestDef genRequestDefForStartAuditInstance();
    static HttpRequestDef genRequestDefForStartAuditInstanceNew();
    static HttpRequestDef genRequestDefForStartDbEncryptInstance();
    static HttpRequestDef genRequestDefForStartDbOmInstance();
    static HttpRequestDef genRequestDefForStopAuditInstance();
    static HttpRequestDef genRequestDefForStopAuditInstanceNew();
    static HttpRequestDef genRequestDefForStopDbEncryptInstance();
    static HttpRequestDef genRequestDefForStopDbOmInstance();
    static HttpRequestDef genRequestDefForSwitchAgent();
    static HttpRequestDef genRequestDefForSwitchAuditDatabase();
    static HttpRequestDef genRequestDefForSwitchAuditDatabaseNew();
    static HttpRequestDef genRequestDefForSwitchRiskRule();
    static HttpRequestDef genRequestDefForSwitchRiskRuleNew();
    static HttpRequestDef genRequestDefForUnbindDbEncryptEip();
    static HttpRequestDef genRequestDefForUnbindDbOmEip();
    static HttpRequestDef genRequestDefForUpdateAuditInstance();
    static HttpRequestDef genRequestDefForUpdateAuditInstanceNew();
    static HttpRequestDef genRequestDefForUpdateAuditRiskBucketPath();
    static HttpRequestDef genRequestDefForUpdateAuditScopeRule();
    static HttpRequestDef genRequestDefForUpdateAuditSecurityGroup();
    static HttpRequestDef genRequestDefForUpdateAuditSecurityGroupNew();
    static HttpRequestDef genRequestDefForUpdateAuditTaskStatus();
    static HttpRequestDef genRequestDefForUpdateAuditTopicReportSchedulerConfig();
    static HttpRequestDef genRequestDefForUpdateDbEncryptInstanceName();
    static HttpRequestDef genRequestDefForUpdateDbOmInstanceName();
    static HttpRequestDef genRequestDefForUpdateSensitiveMaskRule();
    static HttpRequestDef genRequestDefForUploadAuditDbConfig();
    static HttpRequestDef genRequestDefForAddAuditAgentNew();
    static HttpRequestDef genRequestDefForCreateAuditDbAgent();
    static HttpRequestDef genRequestDefForDeleteAuditAgentNew();
    static HttpRequestDef genRequestDefForDownloadAuditAgentNew();
    static HttpRequestDef genRequestDefForListAuditAgentNew();
    static HttpRequestDef genRequestDefForSwitchAgentNew();
    static HttpRequestDef genRequestDefForBatchAddAuditWhitelist();
    static HttpRequestDef genRequestDefForCreateAuditSqlRule();
    static HttpRequestDef genRequestDefForDeleteAuditRuleSql();
    static HttpRequestDef genRequestDefForDeleteAuditWhitelist();
    static HttpRequestDef genRequestDefForListSqlInjectionRulesNew();
    static HttpRequestDef genRequestDefForListWhitelists();
    static HttpRequestDef genRequestDefForSetAuditSqlRuleSwitch();
    static HttpRequestDef genRequestDefForSetSqlRuleRank();
    static HttpRequestDef genRequestDefForUpdateAuditSqlRule();
    static HttpRequestDef genRequestDefForUpdateAuditWhitelist();
    static HttpRequestDef genRequestDefForBatchAddResourceTag();
    static HttpRequestDef genRequestDefForBatchDeleteResourceTag();
    static HttpRequestDef genRequestDefForCountResourceInstanceByTag();
    static HttpRequestDef genRequestDefForListAuditTags();
    static HttpRequestDef genRequestDefForListProjectResourceTags();
    static HttpRequestDef genRequestDefForListResourceInstanceByTag();
};

}
}
}
}

#endif // HUAWEICLOUD_SDK_DBSS_V1_DbssMeta_H_
