#ifndef HUAWEICLOUD_SDK_CFW_V1_CfwMeta_H_
#define HUAWEICLOUD_SDK_CFW_V1_CfwMeta_H_

#include <huaweicloud/core/http/HttpRequestDef.h>
#include <huaweicloud/cfw/v1/CfwExport.h>

namespace HuaweiCloud {
namespace Sdk {
namespace Cfw {
namespace V1 {

using namespace HuaweiCloud::Sdk::Core::Http;

class HUAWEICLOUD_CFW_V1_EXPORT  CfwMeta {
public:
    static HttpRequestDef genRequestDefForCancelCaptureTask();
    static HttpRequestDef genRequestDefForCreateCaptureTask();
    static HttpRequestDef genRequestDefForDeleteCaptureTask();
    static HttpRequestDef genRequestDefForDeleteIpBlacklist();
    static HttpRequestDef genRequestDefForEnableIpBlacklist();
    static HttpRequestDef genRequestDefForExportIpBlacklist();
    static HttpRequestDef genRequestDefForImportIpBlacklist();
    static HttpRequestDef genRequestDefForListCaptureResult();
    static HttpRequestDef genRequestDefForListCaptureTask();
    static HttpRequestDef genRequestDefForListIpBlacklist();
    static HttpRequestDef genRequestDefForListIpBlacklistSwitch();
    static HttpRequestDef genRequestDefForListProjectTags();
    static HttpRequestDef genRequestDefForListResourceTags();
    static HttpRequestDef genRequestDefForRetryIpBlacklist();
    static HttpRequestDef genRequestDefForSaveTags();
    static HttpRequestDef genRequestDefForShowAlarmConfig();
    static HttpRequestDef genRequestDefForShowAntiVirusRule();
    static HttpRequestDef genRequestDefForShowAntiVirusSwitch();
    static HttpRequestDef genRequestDefForUpdateAlarmConfig();
    static HttpRequestDef genRequestDefForUpdateAntiVirusRule();
    static HttpRequestDef genRequestDefForUpdateAntiVirusSwitch();
    static HttpRequestDef genRequestDefForAddAclRule();
    static HttpRequestDef genRequestDefForBatchDeleteAclRules();
    static HttpRequestDef genRequestDefForBatchUpdateAclRuleActions();
    static HttpRequestDef genRequestDefForDeleteAclRule();
    static HttpRequestDef genRequestDefForDeleteAclRuleHitCount();
    static HttpRequestDef genRequestDefForDownloadExportResult();
    static HttpRequestDef genRequestDefForDownloadImportResult();
    static HttpRequestDef genRequestDefForDownloadImportTemplate();
    static HttpRequestDef genRequestDefForExportRuleAcl();
    static HttpRequestDef genRequestDefForImportRuleAcl();
    static HttpRequestDef genRequestDefForListAclRuleHitCount();
    static HttpRequestDef genRequestDefForListAclRuleHitStatus();
    static HttpRequestDef genRequestDefForListAclRules();
    static HttpRequestDef genRequestDefForListRegions();
    static HttpRequestDef genRequestDefForListRuleAclTags();
    static HttpRequestDef genRequestDefForShowExportStatus();
    static HttpRequestDef genRequestDefForShowImportStatus();
    static HttpRequestDef genRequestDefForUpdateAclRule();
    static HttpRequestDef genRequestDefForUpdateAclRuleOrder();
    static HttpRequestDef genRequestDefForAddAddressItem();
    static HttpRequestDef genRequestDefForAddAddressSet();
    static HttpRequestDef genRequestDefForBatchDeleteAddressItems();
    static HttpRequestDef genRequestDefForBatchDeleteAddressSets();
    static HttpRequestDef genRequestDefForDeleteAddressItem();
    static HttpRequestDef genRequestDefForDeleteAddressSet();
    static HttpRequestDef genRequestDefForListAddressItems();
    static HttpRequestDef genRequestDefForListAddressSetDetail();
    static HttpRequestDef genRequestDefForListAddressSets();
    static HttpRequestDef genRequestDefForUpdateAddressSet();
    static HttpRequestDef genRequestDefForUpdateObjectConfigDesc();
    static HttpRequestDef genRequestDefForAddBlackWhiteList();
    static HttpRequestDef genRequestDefForBatchCreateBlackWhiteList();
    static HttpRequestDef genRequestDefForBatchDeleteBlackWhiteLists();
    static HttpRequestDef genRequestDefForDeleteBlackWhiteList();
    static HttpRequestDef genRequestDefForListBlackWhiteLists();
    static HttpRequestDef genRequestDefForUpdateBlackWhiteList();
    static HttpRequestDef genRequestDefForAddCustomDnsServer();
    static HttpRequestDef genRequestDefForAddDomainSet();
    static HttpRequestDef genRequestDefForAddDomains();
    static HttpRequestDef genRequestDefForBatchDeleteDomainSet();
    static HttpRequestDef genRequestDefForDeleteDomainSet();
    static HttpRequestDef genRequestDefForDeleteDomains();
    static HttpRequestDef genRequestDefForListDnsServers();
    static HttpRequestDef genRequestDefForListDomainParseDetail();
    static HttpRequestDef genRequestDefForListDomainParseIp();
    static HttpRequestDef genRequestDefForListDomainResolveIp();
    static HttpRequestDef genRequestDefForListDomainSets();
    static HttpRequestDef genRequestDefForListDomains();
    static HttpRequestDef genRequestDefForShowDomainSetDetail();
    static HttpRequestDef genRequestDefForUpdateDnsServers();
    static HttpRequestDef genRequestDefForUpdateDomainSet();
    static HttpRequestDef genRequestDefForAddEipAlarmWhitelist();
    static HttpRequestDef genRequestDefForChangeEipStatus();
    static HttpRequestDef genRequestDefForListAlarmWhitelist();
    static HttpRequestDef genRequestDefForListEipCount();
    static HttpRequestDef genRequestDefForListEips();
    static HttpRequestDef genRequestDefForShowAutoProtectStatus();
    static HttpRequestDef genRequestDefForSwitchAutoProtectStatus();
    static HttpRequestDef genRequestDefForSwitchFirewallEipProtection();
    static HttpRequestDef genRequestDefForCreateEastWestFirewall();
    static HttpRequestDef genRequestDefForCreateFirewall();
    static HttpRequestDef genRequestDefForCreateTag();
    static HttpRequestDef genRequestDefForDeleteFirewall();
    static HttpRequestDef genRequestDefForDeleteTag();
    static HttpRequestDef genRequestDefForListEastWestFirewall();
    static HttpRequestDef genRequestDefForListFirewallDetail();
    static HttpRequestDef genRequestDefForListFirewallList();
    static HttpRequestDef genRequestDefForListJob();
    static HttpRequestDef genRequestDefForListProtectedVpcs();
    static HttpRequestDef genRequestDefForShowConfigQuota();
    static HttpRequestDef genRequestDefForShowSnFirewallProtectionStatus();
    static HttpRequestDef genRequestDefForUpdateFirewallName();
    static HttpRequestDef genRequestDefForBatchDeleteCustomerIps();
    static HttpRequestDef genRequestDefForBatchUpdateCustomerIpsAction();
    static HttpRequestDef genRequestDefForChangeIpsProtectMode();
    static HttpRequestDef genRequestDefForChangeIpsRuleMode();
    static HttpRequestDef genRequestDefForChangeIpsSwitchStatus();
    static HttpRequestDef genRequestDefForCreateCustomerIps();
    static HttpRequestDef genRequestDefForListAdvancedIpsRules();
    static HttpRequestDef genRequestDefForListCustomerIps();
    static HttpRequestDef genRequestDefForListIpsProtectMode();
    static HttpRequestDef genRequestDefForListIpsRules();
    static HttpRequestDef genRequestDefForListIpsSwitchStatus();
    static HttpRequestDef genRequestDefForShowCustomerIpsInfo();
    static HttpRequestDef genRequestDefForShowIpsUpdateTime();
    static HttpRequestDef genRequestDefForUpdateAdvancedIpsRule();
    static HttpRequestDef genRequestDefForUpdateCustomerIps();
    static HttpRequestDef genRequestDefForBatchCreateIpsWhitelist();
    static HttpRequestDef genRequestDefForBatchDeleteIpsWhitelist();
    static HttpRequestDef genRequestDefForListIpsWhitelists();
    static HttpRequestDef genRequestDefForUpdateIpsWhitelist();
    static HttpRequestDef genRequestDefForListAttackStatistic();
    static HttpRequestDef genRequestDefForListFlowStatistic();
    static HttpRequestDef genRequestDefForShowAccessDetail();
    static HttpRequestDef genRequestDefForShowAccessTop();
    static HttpRequestDef genRequestDefForShowAttackDetail();
    static HttpRequestDef genRequestDefForShowAttackTop();
    static HttpRequestDef genRequestDefForShowAttackTotal();
    static HttpRequestDef genRequestDefForShowAttackTrend();
    static HttpRequestDef genRequestDefForShowFlowDetail();
    static HttpRequestDef genRequestDefForShowFlowTop();
    static HttpRequestDef genRequestDefForShowFlowTrend();
    static HttpRequestDef genRequestDefForShowLogsCount();
    static HttpRequestDef genRequestDefForShowTrafficTrend();
    static HttpRequestDef genRequestDefForAddLogConfig();
    static HttpRequestDef genRequestDefForExportLogs();
    static HttpRequestDef genRequestDefForListAccessControlLogs();
    static HttpRequestDef genRequestDefForListAttackLogs();
    static HttpRequestDef genRequestDefForListFlowLogs();
    static HttpRequestDef genRequestDefForListLogConfig();
    static HttpRequestDef genRequestDefForListLogs();
    static HttpRequestDef genRequestDefForUpdateLogConfig();
    static HttpRequestDef genRequestDefForBatchAddAccounts();
    static HttpRequestDef genRequestDefForBatchRemoveAccounts();
    static HttpRequestDef genRequestDefForEnableMultiAccount();
    static HttpRequestDef genRequestDefForListAccounts();
    static HttpRequestDef genRequestDefForListOrganizationAccounts();
    static HttpRequestDef genRequestDefForListOrganizationTree();
    static HttpRequestDef genRequestDefForBatchDeleteSchedules();
    static HttpRequestDef genRequestDefForCreateSchedule();
    static HttpRequestDef genRequestDefForDeleteSchedule();
    static HttpRequestDef genRequestDefForListSchedules();
    static HttpRequestDef genRequestDefForUpdateSchedule();
    static HttpRequestDef genRequestDefForCreateReportProfile();
    static HttpRequestDef genRequestDefForDeleteReportProfile();
    static HttpRequestDef genRequestDefForListReportHistory();
    static HttpRequestDef genRequestDefForListReportProfiles();
    static HttpRequestDef genRequestDefForShowFirewallReport();
    static HttpRequestDef genRequestDefForShowReportProfile();
    static HttpRequestDef genRequestDefForUpdateReportProfile();
    static HttpRequestDef genRequestDefForAddServiceItems();
    static HttpRequestDef genRequestDefForAddServiceSet();
    static HttpRequestDef genRequestDefForBatchDeleteServiceItems();
    static HttpRequestDef genRequestDefForBatchDeleteServiceSets();
    static HttpRequestDef genRequestDefForDeleteServiceItem();
    static HttpRequestDef genRequestDefForDeleteServiceSet();
    static HttpRequestDef genRequestDefForListServiceItems();
    static HttpRequestDef genRequestDefForListServiceSetDetail();
    static HttpRequestDef genRequestDefForListServiceSets();
    static HttpRequestDef genRequestDefForUpdateServiceSet();
    static HttpRequestDef genRequestDefForBatchCreatePrivateNetworkSegments();
    static HttpRequestDef genRequestDefForBatchDeletePrivateNetworkSegments();
    static HttpRequestDef genRequestDefForChangeEastWestFirewallStatus();
    static HttpRequestDef genRequestDefForListPrivateNetworkSegments();
    static HttpRequestDef genRequestDefForShowEwAssociatedEr();
    static HttpRequestDef genRequestDefForShowEwAssociatedVpc();
    static HttpRequestDef genRequestDefForUpdatePrivateNetworkSegment();
};

}
}
}
}

#endif // HUAWEICLOUD_SDK_CFW_V1_CfwMeta_H_
